apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-kubernetes-webhook
  name: sleeve-webhook
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-kubernetes-webhook
  template:
    metadata:
      labels:
        app: simple-kubernetes-webhook
    spec:
      tolerations:
        - key: acme.com/lifespan-remaining
          operator: Exists
          effect: NoSchedule
      containers:
        - image: simple-kubernetes-webhook:latest
          imagePullPolicy: Never
          name: simple-kubernetes-webhook
          env:
            - name: TLS
              value: "true"
            - name: LOG_LEVEL
              value: "trace"
            - name: LOG_JSON
              value: "false"
            - name: USERNAME_VALIDATION_WHITELIST
              value: "system:node,garbage-collector,pvc-protection-controller,sleeve-system:controller-manager,kube-scheduler,cass-operator,sleeve:controller-user,persistent-volume-binder"
            - name: SLEEVE_MINIO_ENDPOINT
              value: minio-svc.sleeve-system.svc.cluster.local:9000
            - name: SLEEVE_MINIO_ACCESS_KEY
              value: myaccesskey
            - name: SLEEVE_MINIO_SECRET_KEY
              value: mysecretkey
            - name: SLEEVE_MINIO_BUCKET
              value: sleeve2
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: simple-kubernetes-webhook-tls
